### ISSUE TITLE
Unknown host: node.stratio.com

### ISSUE THREAD

**Issue by elenapascual** [Stratio/streaming-cep-engine#30]
Hi!

I came across this error when installing (from binaries) stratio-streaming on a cluster. After some trial and error I found  in the sources that "node.stratio.com" is hardcoded in engine/src/main/resources/config.conf.
Somehow on running time stratio-streaming is picking that config file instead of the good one:  /engine/src/main/config/config.conf. 
How should I fix it?

Thanks in advance!

**Comment by epeinado** [comment]
We have fixed this problem removing the extra configuration (revision fe7818074110d272b58ea572c2d8d344681963c5). If you find some new problem with this, please re-open the issue.

Thanks for all.
